spring:
  datasource:
    hikari:
      data-source-properties:
        serverTimezone: Asia/Seoul
    url: jdbc:mysql://localhost:3306/calendar?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: lurxngmi@gmail.com
    password: Cjssus97!!
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

jwt:
  token:
    expiration:
      time: 3600000 # 1시간 (밀리초 단위)
  secret:
    key: "M2FhYmYzZTlhYmI4N2EwZGJlNjYwZDg0YTk5MGNiMjVjYmI3YzJhNzY4Yjk0ZmEwYmZiZmQ="

logging:
  config: classpath:log4j2/log4j2-prod.yml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
