spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calendar?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # 초기 개발 시에는 update, 운영 환경에서는 validate 사용
    show-sql: false  # SQL 로그 출력
    open-in-view: false

logging:
  config: classpath:log4j2/log4j2-prod.yml